# Generated by Django 2.2.14 on 2023-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SF', 'Science-Fiction'), ('F', 'Fantasi'), ('SD', 'Self-Development')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'Buku Baru'), ('S', 'Buku Bekas')], max_length=1),
        ),
    ]
