# Generated by Django 2.2.14 on 2023-06-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230607_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SF', 'Science-Fiction'), ('F', 'Fantasi'), ('SD', 'Self-Development'), ('R', 'Romance'), ('H', 'Horror'), ('T', 'Misteri'), ('E', 'Education'), ('F', 'Fun-Fiction'), ('K', 'Komik')], max_length=2),
        ),
    ]
